// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0E38BQVb8UoXlemQz2rZZh0tI0-qGf0I',
    appId: '1:340811041906:web:ff0137851f9a2e7b5846eb',
    messagingSenderId: '340811041906',
    projectId: 'chatapp-23c99',
    authDomain: 'chatapp-23c99.firebaseapp.com',
    storageBucket: 'chatapp-23c99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgIEPVXMxIO9tBGy7TwDY2tZnhvZuUC8Y',
    appId: '1:340811041906:android:cb4f8b66b775ece75846eb',
    messagingSenderId: '340811041906',
    projectId: 'chatapp-23c99',
    storageBucket: 'chatapp-23c99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY5t4RAReQWyOXqCbxB9aITTQYbQVpQhs',
    appId: '1:340811041906:ios:15dd75977b08cce35846eb',
    messagingSenderId: '340811041906',
    projectId: 'chatapp-23c99',
    storageBucket: 'chatapp-23c99.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY5t4RAReQWyOXqCbxB9aITTQYbQVpQhs',
    appId: '1:340811041906:ios:15dd75977b08cce35846eb',
    messagingSenderId: '340811041906',
    projectId: 'chatapp-23c99',
    storageBucket: 'chatapp-23c99.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0E38BQVb8UoXlemQz2rZZh0tI0-qGf0I',
    appId: '1:340811041906:web:d6f8f0f68d8230f15846eb',
    messagingSenderId: '340811041906',
    projectId: 'chatapp-23c99',
    authDomain: 'chatapp-23c99.firebaseapp.com',
    storageBucket: 'chatapp-23c99.appspot.com',
  );
}
